### ISSUE TITLE
Comment submission fails with "Failed to send comment."

### ISSUE THREAD

**Issue by rootkea** [almost/hubbub#42]
Hello!

website github repo: https://github.com/rootkea/rootkea.github.io  
Comment page: https://rootkea.me/jekyll/update/2018/12/15/welcome-to-jekyll  

After, submitting comment on the comment page, an alert box pops up with text "Failed to send comment."  

Interestingly, the Hubbub comment system was working perfectly a month ago. Not sure what the exact cause is.

**Comment by rootkea** [comment]
I don't think Heroku application log is required here but nevertheless here it is:  
```
2019-02-09T13:25:57.254803+00:00 heroku[router]: at=info method=OPTIONS path="/api/default/comments" host=hubbub-bot.herokuapp.com request_id=6940e0dd-70d6-488f-a9b9-0c7be46e8bc6 fwd="58.84.15.130" dyno=web.1 connect=0ms service=1ms status=204 bytes=301 protocol=https
2019-02-09T13:25:57.466736+00:00 heroku[router]: at=info method=POST path="/api/default/comments" host=hubbub-bot.herokuapp.com request_id=d35719aa-3952-4d04-9386-a0c51d42564e fwd="58.84.15.130" dyno=web.1 connect=0ms service=1ms status=500 bytes=436 protocol=https
2019-02-09T13:25:57.465549+00:00 app[web.1]: Error: Can't figure out file path for post. URL does not match our regular expression
2019-02-09T13:25:57.465567+00:00 app[web.1]:     at urlPathToSourceFile (/app/server.js:67:11)
2019-02-09T13:25:57.465570+00:00 app[web.1]:     at app.get.prNumber (/app/server.js:126:20)
2019-02-09T13:25:57.465572+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2019-02-09T13:25:57.465574+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/route.js:137:13)
2019-02-09T13:25:57.465575+00:00 app[web.1]:     at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
2019-02-09T13:25:57.465577+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2019-02-09T13:25:57.465579+00:00 app[web.1]:     at /app/node_modules/express/lib/router/index.js:281:22
2019-02-09T13:25:57.465580+00:00 app[web.1]:     at param (/app/node_modules/express/lib/router/index.js:354:14)
2019-02-09T13:25:57.465582+00:00 app[web.1]:     at paramCallback (/app/node_modules/express/lib/router/index.js:401:21)
2019-02-09T13:25:57.465584+00:00 app[web.1]:     at /app/server.js:91:5
```
